default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
development:
  <<: *default
  database: pairbnb_development
test:
  <<: *default
  database: pairbnb_test
production:
  <<: *default
  database: pairbnb_production
